services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/html
      - /var/www/html/node_modules
      - /var/www/html/vendor

    #            - .app/:/var/www/html
    #            - .app/storage:/var/www/html/storage
    #            - ./docker/apache.conf:/etc/apache2/sites-available/000-default.conf
    environment:
      MYSQL_DATABASE: videgrenierenligne
      MYSQL_USER: webapplication
      MYSQL_PASSWORD: 653rag9T
      MYSQL_ROOT_PASSWORD: root
    depends_on:
      - mysql-db
    #        command: >
    #            -   bash -c "php artisan key:generate && apache2-foreground"
    networks:
      - videgrenier

  mysql-db:
    image: mysql:8.0
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_DATABASE: videgrenierenligne
      MYSQL_USER: webapplication
      MYSQL_PASSWORD: 653rag9T
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
      - ./sql/import.sql:/docker-entrypoint-initdb.d/import.sql
    networks:
      - videgrenier

volumes:
  mysql-data:

networks:
  videgrenier:
