services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: bloc-cinq
    ports:
      - "3001:80"
    volumes:
      - .:/var/www/html

    depends_on:
      - db
      - mailpit
    #        command: >
    #            -   bash -c "php artisan key:generate && apache2-foreground"
    networks:
      - videgrenier

  db:
    image: mysql:8.0
    container_name: mysql-db-bloc-cinq
    restart: always
    environment:
      MYSQL_DATABASE: videgrenierenligne
      MYSQL_USER: webapplication
      MYSQL_PASSWORD: 653rag9T
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./sql:/docker-entrypoint-initdb.d
    networks:
      - videgrenier

  mailpit:
    image: axllent/mailpit:latest
    container_name: mailpit
    ports:
      - "8025:8025"
      - "1025:1025"
    networks:
      - videgrenier-prod
      - videgrenier

volumes:
  db_data:

networks:
  videgrenier:
  videgrenier-prod:
