services:
  app-prod:
    build:
      context: .
      dockerfile: Dockerfile.prod
      args:
        BRANCH: main
        #GITHUB_TOKEN: ${GITHUB_TOKEN}
    container_name: bloc-cinq-prod
    ports:
      - "3002:80"
    #   - ./prod:/var/www/html
    environment:
      APP_ENV: prod
    depends_on:
      - db-prod
      - mailpit
    networks:
      - videgrenier

  db-prod:
    image: mysql:8.0
    container_name: mysql-prod
    environment:
      MYSQL_DATABASE: bloc_cinq_prod
      MYSQL_USER: produser
      MYSQL_PASSWORD: prodpass
      MYSQL_ROOT_PASSWORD: rootpassword
    ports:
      - "3308:3306"
    volumes:
      - db_data_prod:/var/lib/mysql
      - ./sql:/docker-entrypoint-initdb.d
    networks:
      - videgrenier

  mailpit:
    image: axllent/mailpit:latest
    container_name: mailpit
    ports:
      - "8025:8025"
      - "1025:1025"
    networks:
      - videgrenier
      - videgrenier-prod

volumes:
  db_data_prod:

networks:
  videgrenier:
  videgrenier-prod:
